#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "usage: findgrep KEYWORD_TO_SEARCH"
else 
  find . -type d -name '.git' -prune -o  -type d -name '.svn' -prune -o   -type d -name 'tmp' -prune -o    -type f -exec grep -dskip $1 {} \; -print
fi

